# Generated by Django 3.2.23 on 2024-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='key_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='課題キー'),
        ),
    ]
