# Generated by Django 3.2.23 on 2024-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0004_oauth2_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=255, verbose_name='space key')),
                ('project_key', models.CharField(max_length=255, verbose_name='project key')),
            ],
        ),
    ]
