# Generated by Django 3.2.23 on 2024-01-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0005_backlogsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=255, verbose_name='space key')),
                ('project_key', models.CharField(max_length=255, verbose_name='project key')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
                ('client_id', models.CharField(max_length=255, verbose_name='client id')),
                ('client_secret', models.CharField(max_length=255, verbose_name='client secret')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.DeleteModel(
            name='BacklogSetting',
        ),
        migrations.DeleteModel(
            name='Oauth2',
        ),
    ]
