# Generated by Django 3.2.23 on 2024-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0006_auto_20240106_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='project id'),
        ),
    ]
