# Generated by Django 3.2.23 on 2024-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0008_auto_20240107_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True, verbose_name='expires_in'),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh_token'),
        ),
    ]
