# Generated by Django 3.2.23 on 2024-01-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0009_auto_20240107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='domain'),
        ),
    ]
