# Generated by Django 3.2.23 on 2024-01-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0010_setting_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='課題種別キー'),
        ),
    ]
