# Generated by Django 3.2.23 on 2024-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0011_issue_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='project key'),
        ),
    ]
