# Generated by Django 3.2.23 on 2024-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogext', '0012_issue_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='project id'),
        ),
    ]
